// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVhmHDqvazjoWXuG2XbIgWb2lyAf-zFHc',
    appId: '1:1052028042977:web:1948d340f2ee069cba01a0',
    messagingSenderId: '1052028042977',
    projectId: 'graduation-lion',
    authDomain: 'graduation-lion.firebaseapp.com',
    storageBucket: 'graduation-lion.appspot.com',
    measurementId: 'G-NPZ70FJE5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZg8sOGTS35PSqNlStMwu6F9b5i-8eonM',
    appId: '1:1052028042977:android:3255ed48ddc5b2c7ba01a0',
    messagingSenderId: '1052028042977',
    projectId: 'graduation-lion',
    storageBucket: 'graduation-lion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZfly91rjUPBU-X39SXbB4KtisK3bp-nw',
    appId: '1:1052028042977:ios:6ff38109dfa06349ba01a0',
    messagingSenderId: '1052028042977',
    projectId: 'graduation-lion',
    storageBucket: 'graduation-lion.appspot.com',
    iosClientId: '1052028042977-mprk6trl8fkmtjdss7jr630ae8dc2l4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationlion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZfly91rjUPBU-X39SXbB4KtisK3bp-nw',
    appId: '1:1052028042977:ios:6ff38109dfa06349ba01a0',
    messagingSenderId: '1052028042977',
    projectId: 'graduation-lion',
    storageBucket: 'graduation-lion.appspot.com',
    iosClientId: '1052028042977-mprk6trl8fkmtjdss7jr630ae8dc2l4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationlion',
  );
}
